name: Dependencies Update

on:
  schedule:
    - cron: "59 5 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm i

      - name: Updating dependencies
        run: pnpm exec npm-check-updates -u --target minor

      - name: Dependencies audit
        run: pnpm audit --fix

      - name: Installing dependencies
        run: pnpm i

      - name: Running ESLint
        run: pnpm run lint

      - name: Running Vitest
        run: pnpm run test

      - name: Running Build
        run: pnpm run build

      - name: Running Build for Storybook
        run: pnpm run build:storybook

      - name: Run command
        uses: ctux/simple-pull-request-gh-action@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch_main_name: "'master'"
          branch_pr_name: "'dependencies-update'"
          commit_message: "'chore(dependencies): automatic updates'"
